version: '3.9'

networks:
  bartholome_gili_devops_1:
    driver: bridge

services:
  
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - bartholome_gili_devops_1

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3001:8000
    networks:
      - bartholome_gili_devops_1

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - bartholome_gili_devops_1